# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d15f403cf78279b85eb9af6f4b6a6777484f4e3f9342b121a7cca38e7e4e31c3f27a2fb58dcde799542dc24bb3af5cc75639c46e9a7e4383afe38a9b5bb42bed

test:
  secret_key_base: eb9a56a39a145c383b8e6100438b2bd8320e75597b2dc911ff4d582e08037eeb67c3a580a04dc792acc9e13dfa0ef3be19bbb4ec2224185136161c4c28be5878

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
